[workspace]
members = [
    "mobile",
    "nodejs", 
    "wasm"
]

[workspace.dependencies]
zkp-circuit = { path = "../zkp-circuit" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
